name: Update CI
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 * * * *"
  repository_dispatch:
    types: [update]
jobs:
  release:
    name: Update I18N
    runs-on: ubuntu-18.04
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      - name: Run update data script
        run: npm run start
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
      - name: Commit new data
        uses: stefanzweifel/git-auto-commit-action@v4.4.0
        with:
          commit_message: ":globe_with_meridians: Update I18N data [skip ci]"
          commit_user_name: Koj Bot
          commit_user_email: bot@koj.co
          commit_author: Koj Bot <bot@koj.co>
